"use strict";

window.EXTRA_ITEMS = [
  // Tailwind CSS
  { course: "words", target: "Tailwind CSS", reading: "テイルウィンド シーエスエス", meaning: "ユーティリティクラスを組み合わせてデザインするCSSフレームワーク", example: "class=\"flex gap-4\"", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "utility-first", reading: "ユーティリティ ファースト", meaning: "小さな役割のクラスを組み合わせる設計方法", example: "p-4 text-center", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "utility class", reading: "ユーティリティ クラス", meaning: "一つのスタイル上の役割を持つクラス", example: "display: flex → flex", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "responsive variant", reading: "レスポンシブ バリアント", meaning: "画面幅に応じてクラスを切り替える接頭辞", example: "md:grid-cols-2", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "breakpoint", reading: "ブレイクポイント", meaning: "レイアウトを切り替える画面幅", example: "sm / md / lg", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "state variant", reading: "ステート バリアント", meaning: "操作や状態に応じてスタイルを変える接頭辞", example: "hover:bg-blue-700", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "dark mode", reading: "ダーク モード", meaning: "暗い配色へ切り替える表示モード", example: "dark:bg-slate-900", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "theme variable", reading: "テーマ バリアブル", meaning: "色や余白などのデザイン値を管理する変数", example: "--color-brand", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "arbitrary value", reading: "アービトラリー バリュー", meaning: "角かっこで任意の値を直接指定する方法", example: "w-[320px]", logo: "./images/frameworks/tailwindcss.svg" },
  { course: "words", target: "Preflight", reading: "プリフライト", meaning: "Tailwind CSSに含まれる基本スタイルの調整", example: "ブラウザ間の初期表示を整える", logo: "./images/frameworks/tailwindcss.svg" },

  // Bootstrap
  { course: "words", target: "Bootstrap", reading: "ブートストラップ", meaning: "部品とレイアウト機能を備えたCSSフレームワーク", example: "btn btn-primary", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "container-fluid", reading: "コンテナー フルイド", meaning: "画面幅いっぱいに広がるBootstrapのコンテナー", example: "class=\"container-fluid\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "Bootstrap container", reading: "ブートストラップ コンテナー", meaning: "内容の幅と左右余白を整える入れ物", example: "class=\"container\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "Bootstrap row", reading: "ブートストラップ ロウ", meaning: "グリッドの列を横方向にまとめる行", example: "class=\"row\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "Bootstrap column", reading: "ブートストラップ カラム", meaning: "12分割グリッドで幅を指定する列", example: "class=\"col-md-6\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "gutter", reading: "ガター", meaning: "グリッドの列と列の間隔", example: "class=\"g-3\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "navbar", reading: "ナビバー", meaning: "サイト内の移動メニューを作る部品", example: "class=\"navbar\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "Bootstrap modal", reading: "ブートストラップ モーダル", meaning: "画面の手前に開くダイアログ部品", example: "class=\"modal\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "accordion", reading: "アコーディオン", meaning: "内容を開閉して表示する部品", example: "class=\"accordion\"", logo: "./images/frameworks/bootstrap.svg" },
  { course: "words", target: "utility API", reading: "ユーティリティ エーピーアイ", meaning: "Bootstrapのユーティリティを追加・変更する仕組み", example: "spacing utilities", logo: "./images/frameworks/bootstrap.svg" },

  // Material UI
  { course: "words", target: "Material UI", reading: "マテリアル ユーアイ", meaning: "React向けのUIコンポーネントライブラリ", example: "<Button>Save</Button>", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "React component", reading: "リアクト コンポーネント", meaning: "Reactで再利用できる画面部品", example: "<Card />", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "MUI prop", reading: "エムユーアイ プロップ", meaning: "コンポーネントへ渡す設定値", example: "variant=\"contained\"", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "sx prop", reading: "エスエックス プロップ", meaning: "Material UIの部品へスタイルを指定するprop", example: "sx={{ p: 2 }}", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "ThemeProvider", reading: "テーマ プロバイダー", meaning: "アプリ全体へMaterial UIのテーマを渡す部品", example: "<ThemeProvider theme={theme}>", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "createTheme", reading: "クリエイト テーマ", meaning: "Material UIのテーマ設定を作る関数", example: "createTheme({ palette: {} })", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "MUI palette", reading: "エムユーアイ パレット", meaning: "テーマで色を管理する設定", example: "palette.primary.main", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "MUI typography", reading: "エムユーアイ タイポグラフィ", meaning: "テーマで書体や文字サイズを管理する設定", example: "typography.fontFamily", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "MUI Grid", reading: "エムユーアイ グリッド", meaning: "画面の行と列を組み立てるレイアウト部品", example: "<Grid container spacing={2}>", logo: "./images/frameworks/material-ui.svg" },
  { course: "words", target: "breakpoint helper", reading: "ブレイクポイント ヘルパー", meaning: "画面幅の条件をテーマから利用する仕組み", example: "theme.breakpoints.up('md')", logo: "./images/frameworks/material-ui.svg" },

  // shadcn/ui
  { course: "words", target: "shadcn/ui", reading: "シャドシーエヌ ユーアイ", meaning: "編集可能なUIコンポーネントをプロジェクトへ追加する仕組み", example: "npx shadcn@latest add button", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "component registry", reading: "コンポーネント レジストリ", meaning: "追加できるコンポーネントの配布元", example: "registry item", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "shadcn CLI", reading: "シャドシーエヌ シーエルアイ", meaning: "コンポーネントを追加・更新するコマンドツール", example: "npx shadcn@latest init", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "components.json", reading: "コンポーネンツ ドット ジェイソン", meaning: "shadcn/uiの構成を保存する設定ファイル", example: "aliases / style / css", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "Button component", reading: "ボタン コンポーネント", meaning: "操作ボタンを作る再利用可能な部品", example: "<Button>Save</Button>", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "Card component", reading: "カード コンポーネント", meaning: "内容をカード状にまとめる部品", example: "<Card><CardContent /></Card>", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "Dialog component", reading: "ダイアログ コンポーネント", meaning: "確認画面などを手前に開く部品", example: "<Dialog><DialogContent /></Dialog>", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "Form component", reading: "フォーム コンポーネント", meaning: "入力・検証・エラー表示をまとめる部品", example: "<FormField />", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "shadcn CSS variables", reading: "シャドシーエヌ シーエスエス バリアブルズ", meaning: "背景色や文字色などを管理するCSS変数", example: "--background / --foreground", logo: "./images/frameworks/shadcn-ui.png" },
  { course: "words", target: "copy and own", reading: "コピー アンド オウン", meaning: "部品のコードを自分のプロジェクトで管理する考え方", example: "導入後に自由に編集する", logo: "./images/frameworks/shadcn-ui.png" },

  // Figma
  { course: "words", target: "Figma", reading: "フィグマ", meaning: "ブラウザ上で共同編集できるデザインツール", example: "Webサイトの画面設計やプロトタイプ制作", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "canvas", reading: "キャンバス", meaning: "フレームや図形を配置する作業領域", example: "デザインを広げる大きな作業スペース", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Figma frame", reading: "フィグマ フレーム", meaning: "画面や部品をまとめる親オブジェクト", example: "Desktop / Mobile", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "layer", reading: "レイヤー", meaning: "文字・画像・図形などの重なりを表す単位", example: "Layersパネルで順番を管理する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Figma section", reading: "フィグマ セクション", meaning: "複数のフレームを目的ごとに整理する領域", example: "Wireframes / Final designs", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Figma page", reading: "フィグマ ページ", meaning: "一つのファイル内でデザインを大きく分類する単位", example: "Draft / Components / Archive", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "auto layout", reading: "オート レイアウト", meaning: "内容に合わせて間隔や大きさを自動調整する機能", example: "Shift + A", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Figma component", reading: "フィグマ コンポーネント", meaning: "ボタンなどを再利用するための元部品", example: "変更を複数画面へ反映する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "instance", reading: "インスタンス", meaning: "コンポーネントから作られた使用中のコピー", example: "文字や一部の設定を変更できる", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "variant", reading: "バリアント", meaning: "同じ部品の状態や種類をまとめる機能", example: "Default / Hover / Disabled", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "component set", reading: "コンポーネント セット", meaning: "複数のバリアントを一つにまとめたもの", example: "ボタンの状態をまとめて管理する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "constraint", reading: "コンストレイント", meaning: "親フレームのサイズ変更時に位置や大きさを保つ設定", example: "Left / Right / Scale", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "prototype", reading: "プロトタイプ", meaning: "画面遷移や操作を試せる見本", example: "ボタンから次の画面へ移動する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "interaction", reading: "インタラクション", meaning: "クリックなどをきっかけに起きる動作", example: "On click → Navigate to", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "overlay", reading: "オーバーレイ", meaning: "現在の画面の上へ重ねて表示する画面", example: "メニューや確認ダイアログ", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Dev Mode", reading: "デブ モード", meaning: "デザインを実装するための情報を確認するモード", example: "サイズ・色・コードを確認する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "inspect panel", reading: "インスペクト パネル", meaning: "選択した要素の寸法やスタイルを調べる領域", example: "width / gap / color", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "Figma variable", reading: "フィグマ バリアブル", meaning: "色や数値などを名前付きで再利用する機能", example: "color/brand/primary", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "design token", reading: "デザイン トークン", meaning: "色・余白・文字サイズなどを名前で管理する値", example: "spacing-md / color-primary", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "team library", reading: "チーム ライブラリ", meaning: "チームで共有する部品やスタイルの保管場所", example: "共通コンポーネントを公開する", logo: "./images/frameworks/figma.png" },

  // Web designer workflow
  { course: "words", target: "wireframe", reading: "ワイヤーフレーム", meaning: "情報とレイアウトを線や箱で示す画面の設計図", example: "色や写真を決める前に構成を確認する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "mockup", reading: "モックアップ", meaning: "完成時の見た目に近いデザイン見本", example: "写真・色・書体を含む静的な画面", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "design comp", reading: "デザイン カンプ", meaning: "クライアント確認や実装に使う完成見本", example: "PC版とスマートフォン版を用意する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "handoff", reading: "ハンドオフ", meaning: "確定したデザインを実装担当者へ引き渡すこと", example: "寸法・素材・仕様も一緒に共有する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "typography", reading: "タイポグラフィー", meaning: "書体・文字サイズ・行間などを整える技術", example: "読みやすさと印象を設計する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "visual hierarchy", reading: "ビジュアル ハイアラーキー", meaning: "重要度が伝わるよう見た目に強弱を付けること", example: "見出しを大きく、補足を小さくする", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "white space", reading: "ホワイト スペース", meaning: "情報を読みやすくするための意図的な余白", example: "要素を詰め込みすぎない", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "grid system", reading: "グリッド システム", meaning: "列や基準線を使って配置を揃える仕組み", example: "12-column grid", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "color palette", reading: "カラー パレット", meaning: "デザインで使用する色の組み合わせ", example: "Primary / Accent / Neutral", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "contrast ratio", reading: "コントラスト レシオ", meaning: "文字色と背景色の明るさの差を表す比率", example: "読みやすさを数値で確認する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "design system", reading: "デザイン システム", meaning: "一貫した画面を作るためのルールと部品の集まり", example: "色・書体・コンポーネントを共有する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "style guide", reading: "スタイル ガイド", meaning: "色・文字・ロゴなどの使用ルールをまとめた資料", example: "ブランド表現の統一に使う", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "user flow", reading: "ユーザー フロー", meaning: "利用者が目的を達成するまでの画面や操作の流れ", example: "商品を見る → カート → 購入", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "sitemap", reading: "サイトマップ", meaning: "Webサイトのページ構成と階層を示す図", example: "トップから各ページの関係を整理する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "information architecture", reading: "インフォメーション アーキテクチャ", meaning: "情報を見つけやすく分類・整理する考え方", example: "ページ構成やメニュー名を設計する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "user persona", reading: "ユーザー ペルソナ", meaning: "想定する利用者を具体的な人物像にしたもの", example: "年齢・目的・困りごとを整理する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "mood board", reading: "ムード ボード", meaning: "目指す雰囲気を写真・色・書体でまとめた資料", example: "デザイン制作前に方向性を共有する", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "responsive layout", reading: "レスポンシブ レイアウト", meaning: "画面幅に合わせて変化するレイアウト", example: "PC・タブレット・スマートフォン", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "design breakpoint", reading: "デザイン ブレイクポイント", meaning: "レイアウトを切り替える基準の画面幅", example: "768pxで二列から一列へ変える", logo: "./images/frameworks/figma.png" },
  { course: "words", target: "design accessibility", reading: "デザイン アクセシビリティ", meaning: "身体や利用環境にかかわらず使いやすく設計すること", example: "色だけに頼らず状態を伝える", logo: "./images/frameworks/figma.png" },

  // Additional CSS properties
  { course: "css", target: "box-sizing", meaning: "幅と高さへborderとpaddingを含めるか決める", example: "box-sizing: border-box;" },
  { course: "css", target: "min-width", meaning: "要素の最小幅", example: "min-width: 240px;" },
  { course: "css", target: "max-height", meaning: "要素の最大高さ", example: "max-height: 80vh;" },
  { course: "css", target: "font-family", meaning: "使用する書体", example: "font-family: sans-serif;" },
  { course: "css", target: "font-style", meaning: "文字を通常体や斜体にする", example: "font-style: italic;" },
  { course: "css", target: "letter-spacing", meaning: "文字と文字の間隔", example: "letter-spacing: .05em;" },
  { course: "css", target: "text-decoration", meaning: "下線などの文字装飾", example: "text-decoration: none;" },
  { course: "css", target: "text-transform", meaning: "英字の大文字・小文字表示", example: "text-transform: uppercase;" },
  { course: "css", target: "white-space", meaning: "空白や改行の扱い", example: "white-space: nowrap;" },
  { course: "css", target: "word-break", meaning: "長い単語の改行方法", example: "word-break: break-all;" },
  { course: "css", target: "list-style", meaning: "リスト記号の種類や表示", example: "list-style: none;" },
  { course: "css", target: "background-color", meaning: "背景色", example: "background-color: #ffffff;" },
  { course: "css", target: "background-image", meaning: "背景画像やグラデーション", example: "background-image: linear-gradient(...);" },
  { course: "css", target: "background-size", meaning: "背景画像の大きさ", example: "background-size: cover;" },
  { course: "css", target: "background-position", meaning: "背景画像の位置", example: "background-position: center;" },
  { course: "css", target: "background-repeat", meaning: "背景画像の繰り返し", example: "background-repeat: no-repeat;" },
  { course: "css", target: "border-width", meaning: "境界線の太さ", example: "border-width: 2px;" },
  { course: "css", target: "border-style", meaning: "境界線の種類", example: "border-style: solid;" },
  { course: "css", target: "border-color", meaning: "境界線の色", example: "border-color: #cccccc;" },
  { course: "css", target: "outline", meaning: "要素の外側へ表示する輪郭線", example: "outline: 3px solid blue;" },
  { course: "css", target: "border-collapse", meaning: "表の境界線を重ねるか決める", example: "border-collapse: collapse;" },
  { course: "css", target: "flex-direction", meaning: "Flex要素を並べる方向", example: "flex-direction: column;" },
  { course: "css", target: "flex-grow", meaning: "余った空間へ伸びる割合", example: "flex-grow: 1;" },
  { course: "css", target: "flex-shrink", meaning: "狭いときに縮む割合", example: "flex-shrink: 0;" },
  { course: "css", target: "flex-basis", meaning: "Flex要素の基準サイズ", example: "flex-basis: 240px;" },
  { course: "css", target: "align-content", meaning: "複数行全体を交差方向に揃える", example: "align-content: center;" },
  { course: "css", target: "justify-items", meaning: "Grid内の各要素を横方向に揃える", example: "justify-items: center;" },
  { course: "css", target: "grid-template-rows", meaning: "Gridの行サイズを定義する", example: "grid-template-rows: auto 1fr;" },
  { course: "css", target: "grid-auto-flow", meaning: "Gridへ要素を配置する方向", example: "grid-auto-flow: column;" },
  { course: "css", target: "order", meaning: "Flex・Grid要素の表示順", example: "order: 2;" },
  { course: "css", target: "z-index", meaning: "重なり順", example: "z-index: 10;" },
  { course: "css", target: "top", meaning: "配置位置の上からの距離", example: "top: 0;" },
  { course: "css", target: "right", meaning: "配置位置の右からの距離", example: "right: 16px;" },
  { course: "css", target: "bottom", meaning: "配置位置の下からの距離", example: "bottom: 0;" },
  { course: "css", target: "left", meaning: "配置位置の左からの距離", example: "left: 50%;" },
  { course: "css", target: "visibility", meaning: "要素の表示・非表示", example: "visibility: hidden;" },
  { course: "css", target: "cursor", meaning: "マウスポインターの形", example: "cursor: pointer;" },
  { course: "css", target: "pointer-events", meaning: "マウス操作を受け取るか決める", example: "pointer-events: none;" },
  { course: "css", target: "user-select", meaning: "文字を選択できるか決める", example: "user-select: none;" },
  { course: "css", target: "object-position", meaning: "画像や動画を切り抜く位置", example: "object-position: center top;" },

  // Instructions for AI
  { course: "sentences", target: "Create a responsive header with a clear navigation menu.", meaning: "分かりやすいメニュー付きのレスポンシブヘッダーを作って", example: "作るものと必要な特徴を伝える" },
  { course: "sentences", target: "Use semantic HTML elements and explain each choice.", meaning: "意味に合ったHTML要素を使い、選んだ理由も説明して", example: "品質条件と説明方法を指定する" },
  { course: "sentences", target: "Write CSS without changing the existing HTML structure.", meaning: "既存のHTML構造を変えずにCSSを書いて", example: "変更してよい範囲を明確にする" },
  { course: "sentences", target: "Make the layout work from 320 pixels to desktop width.", meaning: "320pxからパソコン幅まで崩れないレイアウトにして", example: "確認する画面幅を具体的にする" },
  { course: "sentences", target: "Keep the current colors and improve only the spacing.", meaning: "現在の色は維持し、余白だけを改善して", example: "変えないものを明示する" },
  { course: "sentences", target: "Add accessible labels to every form control.", meaning: "すべてのフォーム部品へアクセシブルなラベルを付けて", example: "アクセシビリティ要件を伝える" },
  { course: "sentences", target: "Use the provided image as the hero background.", meaning: "支給画像をファーストビューの背景に使って", example: "使用する素材と場所を指定する" },
  { course: "sentences", target: "Do not edit files outside the requested folder.", meaning: "指定したフォルダー以外のファイルは編集しないで", example: "作業範囲を制限する" },
  { course: "sentences", target: "List the files you changed and summarize each change.", meaning: "変更ファイルと各変更内容を一覧にして", example: "完了報告の形式を指定する" },
  { course: "sentences", target: "Check the browser console and fix the first error.", meaning: "Consoleを確認し、最初のエラーを修正して", example: "調査場所と優先順位を伝える" },
  { course: "sentences", target: "Compare the result with the reference screenshot.", meaning: "結果を参考スクリーンショットと比較して", example: "品質確認の基準を与える" },
  { course: "sentences", target: "Explain the cause before making any code changes.", meaning: "コードを変更する前に原因を説明して", example: "診断と実装を分ける" },
  { course: "sentences", target: "Show three design options with different layouts.", meaning: "レイアウトの異なるデザイン案を3つ見せて", example: "案の数と違いを指定する" },
  { course: "sentences", target: "Use plain Japanese that high school students can understand.", meaning: "高校生にも分かるやさしい日本語を使って", example: "対象読者と文章の難しさを伝える" },
  { course: "sentences", target: "Keep the design simple and avoid unnecessary animation.", meaning: "シンプルにして不要なアニメーションは避けて", example: "デザイン方針と禁止事項を示す" },
  { course: "sentences", target: "Optimize the images without reducing visible quality.", meaning: "見た目の品質を落とさず画像を軽量化して", example: "品質と容量の両方を指定する" },
  { course: "sentences", target: "Test keyboard navigation and visible focus styles.", meaning: "キーボード操作とフォーカス表示を確認して", example: "操作方法を含めてテストさせる" },
  { course: "sentences", target: "Use CSS Grid and include a fallback for narrow screens.", meaning: "CSS Gridを使い、狭い画面用の表示も用意して", example: "技術と例外条件を指定する" },
  { course: "sentences", target: "Ask questions if the client request is ambiguous.", meaning: "依頼内容が曖昧なら質問して", example: "勝手に判断してほしくない点を伝える" },
  { course: "sentences", target: "Run the relevant tests and report the results.", meaning: "関係するテストを実行して結果を報告して", example: "検証と報告まで依頼する" }
];
